#!/usr/bin/env bash
# ============================================================================
# build-aiven-dump.sh — produce ONE self-contained .sql file (schema + data)
# that recreates the whole rocloud_prod database on a fresh Aiven for
# PostgreSQL service.
#
#   PGPASSWORD='<postgres superuser password>' bash scripts/build-aiven-dump.sh
#
# Output: scripts/aiven-rocloud_prod.sql   (restore with a single psql -f)
#
# WHY the postgres superuser: customers / orders / deliveries / invoices /
# payments are owned by postgres and have RLS enabled. pg_dump runs with
# row_security = off, so a role without BYPASSRLS (rocloud_prod_user) cannot
# read them and the dump aborts. Nothing else here needs superuser.
#
# What the generated file contains, in order:
#   1. the application login role (rocloud_prod_user) + CONNECT on the target DB
#   2. extensions (pgcrypto, uuid-ossp)
#   3. every public table/index/constraint  + ALL ROWS  + sequence positions
#   4. RLS policies (pg_dump emits these after the data, so the COPYs are not
#      filtered while loading)
#   5. grants + default privileges for the app role
#   6. the hangfire schema (empty — the API recreates its tables on startup)
#   7. the current + next two audit_logs partitions
#
# Deliberately NOT included: the hangfire *tables* (transient job state), object
# ownership (on Aiven everything is owned by avnadmin), and tablespaces.
#
# The app role must stay a NON-owner: RLS tenant isolation is what stops one
# tenant reading another's rows, and a table's owner bypasses RLS. Restore as
# avnadmin, run the API as rocloud_prod_user. Never point the API at avnadmin.
# ============================================================================
set -euo pipefail

PGBIN="${PGBIN:-/c/Program Files/PostgreSQL/18/bin}"
PGHOST="${PGHOST:-localhost}"
PGPORT="${PGPORT:-5432}"
SRCDB="${SRCDB:-rocloud_prod}"
SRCUSER="${SRCUSER:-postgres}"          # needs BYPASSRLS — see header
APPROLE="${APPROLE:-rocloud_prod_user}"
APP_PW="${APP_PW:-CHANGE_ME_APP_PASSWORD}"
PGDUMP="$PGBIN/pg_dump.exe"

# INSERTS=1 → emit INSERT statements instead of COPY, and write the pgAdmin file.
# COPY ... FROM stdin is a psql-only construct: its "\." terminator is not SQL, so
# pgAdmin's query tool dies with `syntax error at or near "\"`. INSERTs are plain
# SQL and run anywhere, at the cost of a bigger, slower file.
INSERTS="${INSERTS:-0}"

HERE="$(cd "$(dirname "$0")" && pwd)"
if [ "$INSERTS" = "1" ]; then
  OUT="$HERE/aiven-rocloud_prod-pgadmin.sql"
  DATA_FMT=(--inserts --rows-per-insert=200)
else
  OUT="$HERE/aiven-rocloud_prod.sql"
  DATA_FMT=()
fi
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> dumping $SRCDB (schema + data) as $SRCUSER"
# NB: --exclude-schema=hangfire, NOT --schema=public. Restricting to a schema makes
# pg_dump skip extensions altogether, and the tables default to uuid_generate_v4() /
# gen_random_uuid() — the restore then dies on "function uuid_generate_v4() does not exist".
"$PGDUMP" -U "$SRCUSER" -h "$PGHOST" -p "$PGPORT" -d "$SRCDB" \
  --exclude-schema=hangfire --no-owner --no-privileges --no-tablespaces "${DATA_FMT[@]}" \
  | sed -e '/^\\restrict/d' -e '/^\\unrestrict/d' -e '/^SET transaction_timeout/d' \
        -e '/^CREATE SCHEMA public;$/d' -e "/^COMMENT ON SCHEMA public IS/d" \
  > "$TMP/dump.sql"

# ^ the sed drops statements that would abort the restore on a target where the
#   database already exists (which is exactly the Aiven case — "defaultdb" ships
#   with a public schema you do not own):
#     \restrict / \unrestrict     psql-18-only noise; breaks older psql clients
#     SET transaction_timeout     PG17+ only; unknown GUC on an older server
#     CREATE SCHEMA public        "schema public already exists"
#     COMMENT ON SCHEMA public    "must be owner of schema public"
#   It only matches whole lines of SQL — never COPY data (whose only backslash
#   line is the "\." terminator).

echo "==> assembling $OUT"
{
  cat <<HEADER
-- ════════════════════════════════════════════════════════════════════════════
-- aiven-rocloud_prod.sql — complete ROCloud production database (SCHEMA + DATA)
-- *** GENERATED by scripts/build-aiven-dump.sh — do not hand-edit. ***
--
-- Restores rocloud_prod onto a fresh Aiven for PostgreSQL service.
--
--   1. Create the service in Aiven (PostgreSQL 17 or 18). Aiven gives you the
--      database "defaultdb" and the superuser-ish admin role "avnadmin".
--   2. Restore, as avnadmin, into an EMPTY database:
--
--        psql "postgres://avnadmin:<pw>@<host>:<port>/defaultdb?sslmode=require" \\
--             -v ON_ERROR_STOP=1 -f scripts/aiven-rocloud_prod.sql
--
--   3. Point the API at the APP role, never at avnadmin (see the warning below):
--        ConnectionStrings__Default =
--          Host=<host>;Port=<port>;Database=defaultdb;Username=$APPROLE;
--          Password=<app pw>;SSL Mode=Require;Trust Server Certificate=true
--
-- ⚠ SECURITY — the API must connect as $APPROLE, NOT as avnadmin.
--   customers/orders/deliveries/invoices/payments rely on RLS for tenant
--   isolation, and a table's OWNER bypasses RLS. After this restore avnadmin
--   owns every table, so an API connected as avnadmin would see EVERY tenant's
--   rows. $APPROLE owns nothing and is therefore correctly constrained.
--
-- ⚠ Set the app role's password below before running (or re-run the generator
--   with APP_PW='…'). It is the password that goes in the API connection string.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── 1. application login role ───────────────────────────────────────────────
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$APPROLE') THEN
        CREATE ROLE $APPROLE LOGIN PASSWORD '$APP_PW';
    END IF;
END
\$\$;

-- CONNECT on whichever database this is being restored into (defaultdb on Aiven).
DO \$\$
BEGIN
    EXECUTE format('GRANT CONNECT ON DATABASE %I TO $APPROLE', current_database());
END
\$\$;

-- ─── 2-4. extensions, tables, data, sequences, RLS policies ─────────────────
CREATE SCHEMA IF NOT EXISTS public;
HEADER

  cat "$TMP/dump.sql"

  cat <<FOOTER


-- ─── 5. privileges for the application role ──────────────────────────────────
GRANT USAGE ON SCHEMA public TO $APPROLE;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO $APPROLE;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $APPROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES    TO $APPROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO $APPROLE;

-- ─── 6. hangfire schema (tables are recreated by the API on startup) ─────────
CREATE SCHEMA IF NOT EXISTS hangfire;
GRANT ALL ON SCHEMA hangfire TO $APPROLE;
GRANT ALL ON ALL TABLES    IN SCHEMA hangfire TO $APPROLE;
GRANT ALL ON ALL SEQUENCES IN SCHEMA hangfire TO $APPROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA hangfire GRANT ALL ON TABLES    TO $APPROLE;
ALTER DEFAULT PRIVILEGES IN SCHEMA hangfire GRANT ALL ON SEQUENCES TO $APPROLE;

-- ─── 7. audit_logs partitions: current month + next two ──────────────────────
-- (the dump carries the partitions that existed in prod; this tops them up for
--  whenever the restore actually happens. The audit-log-partition job takes
--  over from here.)
DO \$\$
DECLARE
    m date := date_trunc('month', now())::date;
    i int;
BEGIN
    FOR i IN 0..2 LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS public.audit_logs_%s PARTITION OF public.audit_logs FOR VALUES FROM (%L) TO (%L)',
            to_char(m + (i || ' month')::interval, 'YYYY_MM'),
            (m + (i || ' month')::interval),
            (m + ((i + 1) || ' month')::interval));
    END LOOP;
END
\$\$;

-- new partitions created above are owned by the restoring role → re-grant.
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APPROLE;

-- ─── 8. refresh planner statistics ───────────────────────────────────────────
-- Per-table, NOT a bare "ANALYZE": a bare ANALYZE also targets PostgreSQL's shared
-- catalogs (pg_authid, pg_database, …), which a managed provider's admin role does
-- not own — it still works, but spews "permission denied to analyze" warnings that
-- look like a failed restore. Scoping to the public schema keeps the output clean.
DO \$\$
DECLARE t record;
BEGIN
    FOR t IN SELECT format('%I.%I', schemaname, tablename) AS rel
             FROM pg_tables WHERE schemaname = 'public'
    LOOP
        EXECUTE 'ANALYZE ' || t.rel;
    END LOOP;
END
\$\$;
FOOTER
} > "$OUT"

echo "==> wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
if [ "$APP_PW" = "CHANGE_ME_APP_PASSWORD" ]; then
  echo "!!! the app role password is still the CHANGE_ME_APP_PASSWORD placeholder."
  echo "!!! edit it in $OUT, or re-run with APP_PW='<password>'."
fi
